AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for Churn Prediction EC2 Instance
Resources:
  ChurnPredictionEC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ChurnPredictionEC2Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
      Policies:
        - PolicyName: SNSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:CreateTopic
                  - sns:DeleteTopic
                  - sns:Subscribe
                  - sns:Publish
                  - sns:ListTopics
                  - sns:ListSubscriptionsByTopic
                  - sns:GetTopicAttributes
                  - sns:SetTopicAttributes
                Resource: arn:aws:sns:us-east-1:913524944914:PipelineFailureTopic
        - PolicyName: CloudWatchPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:PutMetricData
                  - cloudwatch:GetMetricData
                  - cloudwatch:ListMetrics
                Resource: '*'
        - PolicyName: SageMakerModelRegistryPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker:CreateModelPackage
                  - sagemaker:DescribeModelPackage
                  - sagemaker:ListModelPackages
                  - sagemaker:DescribePipelineExecution
                  - sagemaker:ListPipelineExecutionSteps
                Resource:
                  - 'arn:aws:sagemaker:us-east-1:913524944914:model-package/ChurnPredictionModelGroup/*'
                  - 'arn:aws:sagemaker:us-east-1:913524944914:pipeline/ChurnPredictionPipeline'
                  - 'arn:aws:sagemaker:us-east-1:913524944914:pipeline/ChurnPredictionPipeline/execution/*'
        - PolicyName: PassRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: iam:PassRole
                Resource: 'arn:aws:iam::913524944914:role/ChurnPredictionEC2Role'
                Condition:
                  StringEquals:
                    iam:PassedToService: sagemaker.amazonaws.com
        - PolicyName: IAMReadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:GetPolicy
                  - iam:GetPolicyVersion
                  - iam:ListPolicies
                  - iam:ListPolicyVersions
                Resource: 'arn:aws:iam::913524944914:policy/*'
Outputs:
  RoleArn:
    Description: ARN of the ChurnPredictionEC2Role
    Value: !GetAtt ChurnPredictionEC2Role.Arn